-- CreateTable
CREATE TABLE `Item` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `itemno` VARCHAR(8) NOT NULL,
    `category` ENUM('OPP', 'BTR', 'NXY') NOT NULL DEFAULT 'OPP',
    `date` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `schedule` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `estimate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `act` VARCHAR(191) NOT NULL DEFAULT '-',
    `to` ENUM('LMM', 'XYP', 'LTX') NOT NULL DEFAULT 'LMM',
    `title` VARCHAR(6) NOT NULL,
    `type` VARCHAR(3) NOT NULL,
    `info` VARCHAR(191) NOT NULL DEFAULT '-/-',
    `alert` VARCHAR(191) NOT NULL DEFAULT 'NA',
    `deptA` VARCHAR(191) NOT NULL DEFAULT 'NA',
    `deptB` VARCHAR(191) NOT NULL DEFAULT '-/-',
    `deptC` VARCHAR(191) NOT NULL DEFAULT '-/-',

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
